### PR TITLE
Refactor chains/forwarder to use Options pattern

### PR DESCRIPTION
**Pull request by bszirtes**
## Description

Refactoring chains/forwarder using the Functional Options Pattern, just as it has been implemented in the sdk.

## Issue link

https://github.com/networkservicemesh/sdk-ovs/issues/319

## How Has This Been Tested?

- [ ] Added unit testing to cover
- [X] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [ ] Bug fix
- [ ] New functionality
- [ ] Documentation
- [X] Refactoring
- [ ] CI

### CODE REVIEW

**Review by denis-tingaikin — APPROVED** [review]
LGTM. 

Have you tested it with integration tests?

**Comment by bszirtes** [comment]
> LGTM.
> 
> Have you tested it with integration tests?

Yes, I did.

**Comment by denis-tingaikin** [comment]
I'm fine with merging this.

@ljkiraly Do you have any comments on the PR?

**Review by ljkiraly — APPROVED** [review]
It's fine.

**Pull request merged**
